FROM openjdk:17-jdk
USER root
RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs

USER jenkins
LABEL maintainer="sixtale"
ARG JAR_FILE=gradle/wrapper/gradle-wrapper.jar
ADD ${JAR_FILE} docker-springboot.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/docker-springboot.jar"]
