pipeline {
    agent any
    environment{
        TARGET_HOST = "D108-INFINITY@i11d108.p.ssafy.io"
        IMAGE_NAME = "jenkins/jenkins:2.469"
        CONTAINER_NAME ="jenkins"
        LAST_VERSION = "1.0"
        NEW_VERSION = "1.0"
        PROJECT_PATH = "/home/ubuntu/jenkins-data"
    }
    stages {
        stage('Clone') {
            steps {
                git branch: 'master', credentialsId: 'd108-sixtale' ,url: 'https://lab.ssafy.com/s11-webmobile1-sub2/S11P12D108'
            }
        }
        stage('Build') {
            steps {
                dir("./Backend/test"){
                    sh 'chmod +x gradlew'
                    sh  './gradlew clean build'
                }
            }
        }
        stage('Test') {
            steps {
                 echo  '테스트 단계와 관련된 몇 가지 단계를 수행합니다.'
            }
        }
        stage('Copy build file'){
            steps{
                dir("./backEnd/SIXTALEBackEnd"){
                    sshagent (credentials: 'd108-sixtale'){
                        sh 'scp -o StrictHostKeyChecking=no ./deploy/Dockerfile ${TARGET_HOST}:${PROJECT_PATH}'
                        sh 'scp -o StrictHostKeyChecking=no ./build/libs/test.jar ${TARGET_HOST}:${PROJECT_PATH}'
                    }
                }
            }
        }
        stage('Stop process'){
            steps{
                sshagent (credentials: 'd108-sixtale'){
                    script{
                        try{
                            sh'''
                             ssh -o StrictHostKeyChecking=no ${TARGET_HOST} "docker rm -f ${CONTAINER_NAME}"
                             ssh -o StrictHostKeyChecking=no ${TARGET_HOST} "docker rmi ${IMAGE_NAME}:${LAST_VERSION}"
                             '''
                        } catch (e){
                            echo 'Remove Container Failed : ${CONTAINER_NAME}'
                        }
                    }

                }
            }
        }
        stage('Deploy'){
            steps{
                sshagent (credentials: 'd108-sixtale'){
                   sh'''
                   ssh -o StrictHostKeyChecking=no ${TARGET_HOST} "docker build --tag ${IMAGE_NAME}:${NEW_VERSION} --build-arg ARG_PROFILE=test ${PROJECT_PATH}"
                   ssh -o StrictHostKeyChecking=no ${TARGET_HOST} "docker run -v server-file-test:/file --name ${CONTAINER_NAME} -p 8888:8888 -d ${IMAGE_NAME}:${NEW_VERSION}"
                   '''
                }
            }
        }
    }
}